### ISSUE TITLE
OpenFileModal: Shows protected system files

### ISSUE THREAD

**Issue by JeppeSRC** [Geno-IDE/Geno#42]
The file modal shows system files and folders which are normally hidden. Crashes when trying to access them, I guess this is the same for normal files and folders that the user don't have access to.

I've only tested it on Windows.

**Comment by theXnoob** [comment]
Can you tell a file or folder so i can use them for testing

**Comment by JeppeSRC** [comment]
There's no specific folder, it's all of them. The problem isn't really that they are showing, it's that it crashes when you try to open them,

**Comment by theXnoob** [comment]
the folder which are in the c drive like system32??

**Comment by JeppeSRC** [comment]
Those aren't protected folders, but the user might not have access to them.

"System Volume Information" is a folder that is normally hidden.
