### ISSUE TITLE
Prebuilt Windows binary, please

### ISSUE THREAD

**Issue by 3oheicrw** [Geno-IDE/Geno#69]
I don't want to build from source. Please consider providing prebuilt Windows binary. Thanks.

**Comment by 3oheicrw** [comment]
Anyone care about this?

**Comment by 3oheicrw** [comment]
Anyone care about this?

**Comment by Gaztin** [comment]
Hey! Sorry for late response. I appreciate that you want to use this application, but I'm afraid I don't want to throw up a binary when the product isn't finished or even very useful. And frankly, I'm not actively working on this project at the moment. I hope that clears things up for you.
